-- Switch to the ACCOUNTADMIN role

USE ROLE HOL_ROLE;
USE WAREHOUSE HOL_WH1;

-- Switch to the COVID_VACCINATIONS schema
USE SCHEMA COVID_VACCINATIONS;

-- Create a new table and populate it with data up to January 1, 2023
CREATE TABLE HOL_DB1.COVID_VACCINATIONS.COVID_VACCINE AS
SELECT * FROM COVID19_DATA.PUBLIC.OWID_VACCINATIONS
WHERE DATE <= '2023-01-01';


-- Select * from HOL_DB1.COVID_VACCINATIONS.COVID_VACCINE limit 1000;