-- Create a view in the analytics schema
CREATE VIEW HOL_DB1.ANALYTICS.COVID_WORLDWIDE_VIEW AS
SELECT
    t1.COUNTRY,
    t1.TOTAL_CASES,
    t1.DEATHS,
    t1.CASES_PER_DAY,
    t1.MORTALITY_RATE,
    t2.TOTAL_VACCINATIONS,
    t2.PEOPLE_VACCINATED,
    t2.PEOPLE_FULLY_VACCINATED,
    t2.DAILY_VACCINATIONS
FROM
    HOL_DB1.COVID_WORLDWIDE.CLEANED_WORLD_HEALTH_TESTS t1
JOIN
    HOL_DB1.COVID_VACCINATIONS.COVID_VACCINE t2
ON
    t1.DATE = t2.DATE AND t1.COUNTRY_REGION = t2.COUNTRY_REGION
WHERE
    t1.TOTAL_CASES > 0
    AND t1.DEATHS IS NOT NULL
    AND t1.TOTAL_CASES IS NOT NULL
    AND t2.TOTAL_VACCINATIONS IS NOT NULL
    AND t2.PEOPLE_VACCINATED IS NOT NULL
    AND t2.PEOPLE_FULLY_VACCINATED IS NOT NULL
    AND t1.COUNTRY_REGION = 'United States';
