
USE ROLE HOL_ROLE;
USE WAREHOUSE HOL_WH1;

Select * From RETAILERS_AND_DISTRIBUTORS.PUBLIC.HARMONIZED_RETAILER_SALES Limit 100; 

-- Step 2: Filter out null values and create a new table
-- Step 1: Create a new table
CREATE TABLE HOL_DB1.RETAIL.RETAILER_SALES AS
SELECT *
FROM RETAILERS_AND_DISTRIBUTORS.PUBLIC.HARMONIZED_RETAILER_SALES
LIMIT 27000

-- DROP TABLE IF EXISTS HOL_DB1.RETAIL.RETAILER_SALES

