SELECT
    c.COUNTRY,
    c.DATE,
    r.DATE_KEY,
    c.TOTAL_CASES,
    SUM(c.DEATHS) AS DEATHS,
    SUM(r.SALES_AMOUNT) AS TOTAL_SALES_AMOUNT

FROM 
    HOL_DB1.COVID_WORLDWIDE.CLEANED_WORLD_HEALTH_TESTS c
JOIN 
    HOL_DB1.RETAIL.RETAILER_SALES r 
    ON c.DATE = r.DATE_KEY
WHERE 
    c.COUNTRY_REGION = 'United States'
GROUP BY  
    c.COUNTRY,
    c.DATE,
    r.DATE_KEY,
    c.TOTAL_CASES
ORDER BY
    c.DATE;

    









-- SELECT 
--     v.DATE,
--     v.COUNTRY_REGION,
--     v.TOTAL_VACCINATIONS,
--     v.PEOPLE_FULLY_VACCINATED,
--     v.PERCENT_FULLY_VACCINATED,
--     v.ROLLING_AVG_DAILY_VACCINATIONS,
--     r.RETAILER,
--     r.SALES_AMOUNT,
--     AVG(r.SALES_AMOUNT) OVER (PARTITION BY v.COUNTRY_REGION ORDER BY v.DATE) AS AVG_SALES_AMOUNT,
--     SUM(v.PEOPLE_FULLY_VACCINATED) OVER (PARTITION BY v.COUNTRY_REGION ORDER BY v.DATE) AS CUMULATIVE_FULLY_VACCINATED,
--     SUM(r.SALES_AMOUNT) OVER (PARTITION BY v.COUNTRY_REGION ORDER BY v.DATE) AS CUMULATIVE_SALES_AMOUNT
-- FROM 
--     HOL_DB1.COVID_VACCINATIONS.COVID_VACCINE v
-- JOIN 
--     HOL_DB1.RETAIL.RETAILER_SALES r 
--     ON v.COUNTRY_REGION = r.MARKET_KEY
-- WHERE 
--     v.COUNTRY_REGION = 'United States' -- Example filter, can be adjusted based on the analysis requirement
-- ORDER BY 
--     v.COUNTRY_REGION, 
--     v.DATE
-- Limit 10000