SELECT 
    v.DATE,
    v.COUNTRY_REGION,
    v.PERCENT_FULLY_VACCINATED,
    r.PRODUCT,
    r.SALES_AMOUNT,
    SUM(r.SALES_AMOUNT) OVER (PARTITION BY v.COUNTRY_REGION, r.PRODUCT ORDER BY v.DATE) AS PRODUCT_CATEGORY_SALES,
    AVG(v.PERCENT_FULLY_VACCINATED) OVER (PARTITION BY v.COUNTRY_REGION, r.PRODUCT ORDER BY v.DATE) AS AVG_VACCINATION_RATE,
    COUNT(*) OVER (PARTITION BY v.COUNTRY_REGION, r.PRODUCT) AS DAYS_COUNT
FROM 
    HOL_DB1.COVID_VACCINATIONS.COVID_VACCINE v
JOIN 
    HOL_DB1.RETAIL.RETAILER_SALES r 
    ON v.DATE = r.DATE_KEY
WHERE 
    v.COUNTRY_REGION = 'United States'
GROUP BY 
    v.DATE, 
    v.COUNTRY_REGION,
    v.PERCENT_FULLY_VACCINATED,
    r.PRODUCT,
    r.SALES_AMOUNT
ORDER BY 
    v.COUNTRY_REGION, 
    r.PRODUCT, 
    v.DATE;