SELECT 
    v.DATE,
    v.COUNTRY_REGION,
    v.PERCENT_FULLY_VACCINATED,
    r.RETAILER,
    r.PRODUCT,
    AVG(r.SALES_AMOUNT) AS AVG_SALES_AMOUNT,
    MAX(r.SALES_AMOUNT) AS MAX_SALES_AMOUNT,
    MIN(r.SALES_AMOUNT) AS MIN_SALES_AMOUNT,
    COUNT(*) AS TRANSACTION_COUNT
FROM 
    HOL_DB1.COVID_VACCINATIONS.COVID_VACCINE v
JOIN 
    HOL_DB1.RETAIL.RETAILER_SALES r 
    ON v.DATE = r.DATE_KEY
WHERE 
    v.COUNTRY_REGION = 'United States'
GROUP BY 
    v.DATE, 
    v.COUNTRY_REGION,
    v.PERCENT_FULLY_VACCINATED,
    r.RETAILER,
    r.PRODUCT
ORDER BY 
    v.COUNTRY_REGION, 
    r.PRODUCT, 
    v.DATE;
