SELECT 
    r.PRODUCT,
    AVG(r.SALES_AMOUNT) AS AVG_SALES_AMOUNT,
    MAX(r.SALES_AMOUNT) AS MAX_SALES_AMOUNT,
    MIN(r.SALES_AMOUNT) AS MIN_SALES_AMOUNT,
    COUNT(*) AS TRANSACTION_COUNT
FROM 
    HOL_DB1.RETAIL.RETAILER_SALES r
WHERE 
    r.DATE_KEY BETWEEN TO_DATE('2021-01-01', 'YYYY-MM-DD') AND TO_DATE('2022-01-31', 'YYYY-MM-DD')
GROUP BY 
    r.PRODUCT
ORDER BY 
    AVG_SALES_AMOUNT DESC;
