SELECT 
    c.COUNTRY,
    c.DATE,
    c.TOTAL_CASES,
    r.SALES_AMOUNT,
    NORMALIZE_SALES_BY_COVID_CASES(r.SALES_AMOUNT, c.TOTAL_CASES) AS NORMALIZED_SALES
FROM 
    HOL_DB1.COVID_WORLDWIDE.CLEANED_WORLD_HEALTH_TESTS c
JOIN 
    HOL_DB1.RETAIL.RETAILER_SALES r 
    ON c.COUNTRY = r.RETAILER AND c.DATE = r.DATE_KEY;