-- Update columns with COALESCE to handle null values
UPDATE HOL_DB1.COVID_VACCINATIONS.COVID_VACCINE
SET
  TOTAL_VACCINATIONS = COALESCE(TOTAL_VACCINATIONS, 0),
  PEOPLE_VACCINATED = COALESCE(PEOPLE_VACCINATED, 0),
  PEOPLE_FULLY_VACCINATED = COALESCE(PEOPLE_FULLY_VACCINATED, 0),
  DAILY_VACCINATIONS = COALESCE(DAILY_VACCINATIONS, 0);

-- Add a new column for the percentage of people fully vaccinated
ALTER TABLE HOL_DB1.COVID_VACCINATIONS.COVID_VACCINE
ADD COLUMN PERCENT_FULLY_VACCINATED DECIMAL(5,2);

-- Calculate the percentage of people fully vaccinated
UPDATE HOL_DB1.COVID_VACCINATIONS.COVID_VACCINE
SET PERCENT_FULLY_VACCINATED = 
    CASE 
        WHEN (PEOPLE_VACCINATED + PEOPLE_FULLY_VACCINATED) > 0 
            THEN (PEOPLE_FULLY_VACCINATED / (PEOPLE_VACCINATED + PEOPLE_FULLY_VACCINATED)) * 100
        ELSE 0  -- or NULL, depending on your preference
    END;

-- Extract Year from Date
ALTER TABLE HOL_DB1.COVID_VACCINATIONS.COVID_VACCINE
ADD COLUMN YEAR INT;

-- Update the new column with the extracted year
UPDATE HOL_DB1.COVID_VACCINATIONS.COVID_VACCINE
SET YEAR = EXTRACT(YEAR FROM DATE);

-- Extract Month from Date
ALTER TABLE HOL_DB1.COVID_VACCINATIONS.COVID_VACCINE
ADD COLUMN MONTH INT;

-- Update the new column with the extracted month
UPDATE HOL_DB1.COVID_VACCINATIONS.COVID_VACCINE
SET MONTH = EXTRACT(MONTH FROM DATE);

-- Calculate 7-day Rolling Average of Daily Vaccinations
ALTER TABLE HOL_DB1.COVID_VACCINATIONS.COVID_VACCINE
ADD COLUMN ROLLING_AVG_DAILY_VACCINATIONS FLOAT;

-- Calculate and update the new column with the 7-day Rolling Average
UPDATE HOL_DB1.COVID_VACCINATIONS.COVID_VACCINE
SET ROLLING_AVG_DAILY_VACCINATIONS = CTE.ROLLING_AVG
FROM (
  SELECT 
    DATE,
    AVG(DAILY_VACCINATIONS) OVER (ORDER BY DATE ROWS BETWEEN 6 PRECEDING AND CURRENT ROW) AS ROLLING_AVG
  FROM HOL_DB1.COVID_VACCINATIONS.COVID_VACCINE
) CTE
WHERE HOL_DB1.COVID_VACCINATIONS.COVID_VACCINE.DATE = CTE.DATE;

-- Perform some statistical analysis
-- Calculate the average daily vaccinations per country
SELECT COUNTRY_REGION, AVG(DAILY_VACCINATIONS) AS avg_daily_vaccinations
FROM HOL_DB1.COVID_VACCINATIONS.COVID_VACCINE
GROUP BY COUNTRY_REGION;

-- Calculate the total vaccinations per country, year, and month
SELECT COUNTRY_REGION, YEAR, MONTH, SUM(TOTAL_VACCINATIONS) AS TOTAL_VACCINATIONS
FROM HOL_DB1.COVID_VACCINATIONS.COVID_VACCINE
GROUP BY COUNTRY_REGION, YEAR, MONTH;

-- -- Display the final table
SELECT * FROM HOL_DB1.COVID_VACCINATIONS.COVID_VACCINE limit 1000;



-- ALTER TABLE HOL_DB1.COVID_VACCINATIONS.COVID_VACCINE
-- DROP COLUMN VACCINES, SOURCE_WEBSITE, LAST_UPDATE_DATE, LAST_REPORTED_FLAG;