CREATE VIEW HOL_DB1.ANALYTICS.COVID_VACCINATIONS_VIEW AS
SELECT
    t2.YEAR,
    t2.MONTH,
    t2.COUNTRY_REGION,
    SUM(t2.TOTAL_VACCINATIONS) AS TOTAL_VACCINATIONS_BY_COUNTRY,
    AVG(t2.DAILY_VACCINATIONS) AS AVG_DAILY_VACCINATIONS_BY_COUNTRY
FROM
    HOL_DB1.COVID_VACCINATIONS.COVID_VACCINE t2
WHERE
    t2.TOTAL_VACCINATIONS IS NOT NULL
    AND t2.PEOPLE_VACCINATED IS NOT NULL
    AND t2.PEOPLE_FULLY_VACCINATED IS NOT NULL
GROUP BY
    t2.YEAR,
    t2.MONTH,
    t2.COUNTRY_REGION;


